export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FINISH = 'AUTH_FINISH';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_STATE_RESET = 'AUTH_STATE_RESET';

export const SENSOR_START = 'SENSOR_START';
export const SENSOR_POST_SUCCESS = 'SENSOR_POST_SUCCESS';
export const SENSORS_GET_SUCCESS = 'SENSORS_GET_SUCCESS';
export const SENSOR_GET_SUCCESS = 'SENSOR_GET_SUCCESS';
export const SENSOR_GET_DATA_SUCCESS = 'SENSOR_GET_DATA_SUCCESS';
export const SENSOR_PATCH_SUCCESS = 'SENSOR_PATCH_SUCCESS';
export const SENSOR_FINISH = 'SENSOR_FINISH';
export const SENSOR_FAIL = 'SENSOR_FAIL';

export const POINT_START = 'POINT_START';
export const POINT_POST_SUCCESS = 'POINT_POST_SUCCESS';
export const POINTS_GET_SUCCESS = 'POINTS_GET_SUCCESS';
export const POINT_GET_SUCCESS = 'POINT_GET_SUCCESS';
export const POINT_GET_SPARK_DATA_SUCCESS = 'POINT_GET_SPARK_DATA_SUCCESS';
export const POINT_PATCH_SUCCESS = 'POINT_PATCH_SUCCESS';
export const POINT_FINISH = 'POINT_FINISH';
export const POINT_FAIL = 'POINT_FAIL';
