const sites = [
    { code: 'COC', site: 'Control Centre' },
    { code: 'QRD', site: 'Queens Road Depot' },
    { code: 'TRD', site: 'Trafford Depot' },
    { code: 'ABM', site: 'Abraham Moss area' },
    { code: 'AIR', site: 'Manchester Airport area' },
    { code: 'ALT', site: 'Altrincham area' },
    { code: 'ANC', site: 'Anchorage area' },
    { code: 'ASH', site: 'Ashton-under-lyne area' },
    { code: 'ASM', site: 'Ashton Moss area' },
    { code: 'ASW', site: 'Ashton West area' },
    { code: 'AUD', site: 'Audenshaw area' },
    { code: 'BAG', site: 'Baguley area' },
    { code: 'BCH', site: 'Benchill area' },
    { code: 'BDW', site: 'Broadway area' },
    { code: 'BKV', site: 'Bowker Vale area' },
    { code: 'BMR', site: 'Barlow Moor road area' },
    { code: 'BOB', site: 'Besses o\'th\' Barn area' },
    { code: 'BRK', site: 'Brooklands area' },
    { code: 'BRT', site: 'Burton Road area' },
    { code: 'BRY', site: 'Bury area' },
    { code: 'CEP', site: 'Central Park area' },
    { code: 'CER', site: 'Cemetery Road area' },
    { code: 'CHO', site: 'Chorlton area' },
    { code: 'CLA', site: 'Clayton Hall area' },
    { code: 'CNK', site: 'Cornbrook area' },
    { code: 'COL', site: 'Collyhurst area' },
    { code: 'CRO', site: 'Crossacres area' },
    { code: 'CRP', site: 'Crumpsall area' },
    { code: 'DAN', site: 'Dane Road area' },
    { code: 'DCF', site: 'Deansgate Castlefield area' },
    { code: 'DDV', site: 'Didsbury Village area' },
    { code: 'DER', site: 'Derker area' },
    { code: 'DYL', site: 'Droylsden area' },
    { code: 'ECC', site: 'Eccles area' },
    { code: 'EDD', site: 'East Didsbury area' },
    { code: 'EDL', site: 'Edge Lane area' },
    { code: 'EVC', site: 'Barton Dock Road area' },
    { code: 'EXQ', site: 'Exchange Quay area' },
    { code: 'EXS', site: 'Exchange Square area' },
    { code: 'FAL', site: 'Failsworth area' },
    { code: 'FIR', site: 'Firswood area' },
    { code: 'FRE', site: 'Freehold area' },
    { code: 'HBC', site: 'Harbour City area' },
    { code: 'HGS', site: 'Hagside area' },
    { code: 'HOL', site: 'Hollinwood area' },
    { code: 'HOT', site: 'Holt Town area' },
    { code: 'HPK', site: 'Heaton Park area' },
    { code: 'HST', site: 'High Street area' },
    { code: 'IRK', site: 'Irk Valley area' },
    { code: 'IWM', site: 'Imperial War Museum area' },
    { code: 'KIN', site: 'Kingsway Business Park area' },
    { code: 'LDW', site: 'Ladywell area' },
    { code: 'LGW', site: 'Langworthy area' },
    { code: 'MAR', site: 'Martinscroft area' },
    { code: 'MEC', site: 'MediaCityUK area' },
    { code: 'MIL', site: 'Milnrow area' },
    { code: 'MKT', site: 'Market Street area' },
    { code: 'MON', site: 'Monsall area' },
    { code: 'MRD', site: 'Moor Road area' },
    { code: 'MST', site: 'Mosley Street area' },
    { code: 'NAV', site: 'Navigation Road area' },
    { code: 'NEB', site: 'Newbold area' },
    { code: 'NEH', site: 'Newhey area' },
    { code: 'NHM', site: 'Newton Heath and Moston area' },
    { code: 'NIS', site: 'New Islington area' },
    { code: 'NMR', site: 'Northern Moor area' },
    { code: 'OHC', site: 'Oldham Central area' },
    { code: 'OHK', site: 'Oldham King Street area' },
    { code: 'OHM', site: 'Oldham Mumps area' },
    { code: 'OLD', site: 'Old Trafford area' },
    { code: 'PAR', site: 'Parkway area' },
    { code: 'PCG', site: 'Piccadilly Gardens area' },
    { code: 'PIC', site: 'Piccadilly Station area' },
    { code: 'PLH', site: 'Peel Hall area' },
    { code: 'POM', site: 'Pomona area' },
    { code: 'PRS', site: 'Prestwich area' },
    { code: 'QNS', site: 'Queens road area' },
    { code: 'QRA', site: 'Queens road depot area' },
    { code: 'RAD', site: 'Radcliffe area' },
    { code: 'RIG', site: 'Rig area' },
    { code: 'RBN', site: 'Robinswood road area' },
    { code: 'ROC', site: 'Rochdale railway station area' },
    { code: 'RTC', site: 'Rochdale town centre area' },
    { code: 'RTH', site: 'Roundthorn area' },
    { code: 'SAL', site: 'Sale area' },
    { code: 'SAQ', site: 'Salford Quays area' },
    { code: 'SHC', site: 'Shaw and Crompton area' },
    { code: 'SHD', site: 'Shadowmoss area' },
    { code: 'SHL', site: 'Shudehill area' },
    { code: 'SOC', site: 'South Chadderton area' },
    { code: 'SPC', site: 'Ethiad campus area' },
    { code: 'SPS', site: 'St Peters Square area' },
    { code: 'STR', site: 'Stretford area' },
    { code: 'SWP', site: 'Sale Water park area' },
    { code: 'SWR', site: 'St Werburgh\'s road area' },
    { code: 'RIG', site: 'Test Rig' },
    { code: 'TFB', site: 'Trafford bar area' },
    { code: 'TFD', site: 'Trafford depot area' },
    { code: 'TMP', site: 'Timperley area' },
    { code: 'TRC', site: 'intu Trafford Centre area' },
    { code: 'VEL', site: 'Velopark area' },
    { code: 'VIC', site: 'Victoria area' },
    { code: 'VLG', site: 'Village area' },
    { code: 'WDD', site: 'West Didsbury area' },
    { code: 'WFD', site: 'Whitefield area' },
    { code: 'WPK', site: 'Wythenshawe park area' },
    { code: 'WSD', site: 'Wharfside area' },
    { code: 'WST', site: 'Weaste area' },
    { code: 'WTH', site: 'Withington area' },
    { code: 'WWD', site: 'Westwood area' }
];

export default sites;